import React from "react";
import Image from "next/image";

import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>DevInfo | Felipe Battistotti</title>
        <meta name="google-site-verification" content="4YTM9hykvzsweTONT0RJliVYAO1kMBioSB61lAVoUbE" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div>
          <Image
            alt="Felipe Battistotti"
            src="https://avatars.githubusercontent.com/u/61482397?v=4"
            height={220}
            width={220}
            quality={100}
            priority={true}
            className={styles.photo}
          />
        </div>

        <span className={styles.description}>
          Felipe Battistotti
        </span>
        <code className={styles.code}>Full Stack Developer</code>

        <div className={styles.grid}>
          <a
            href="https://github.com/FelipeBattistotti"
            target="_blank"
            rel="noreferrer"
            className={styles.cardGitHub}
          >
            <h2>GitHub &rarr;</h2>
            <p>Projetos profissionais e pessoais</p>
          </a>

          <a
            href="mailto:felipe.battistotti@gmail.com"
            target="_blank"
            rel="noreferrer"
            className={styles.cardEmail}
          >
            <h2>E-mail &rarr;</h2>
            <p>Encaminhe um e-mail para Felipe Battistotti</p>
          </a>

          <a
            href="https://www.linkedin.com/in/felipe-battistotti"
            target="_blank"
            rel="noreferrer"
            className={styles.card}
          >
            <h2>LinkedIn &rarr;</h2>
            <p>Perfil profissional</p>
          </a>

          <a
            href="https://www.youtube.com/channel/UCCT10EqcYzg8KcbxmF64cuA"
            target="_blank"
            rel="noreferrer"
            className={styles.cardYouTube}
          >
            <h2>YouTube &rarr;</h2>
            <p>
              Canal do YouTube
            </p>
          </a>

          <a
            href="https://www.instagram.com/felipebattistotti"
            target="_blank"
            rel="noreferrer"
            className={styles.cardInsta}
          >
            <div className={styles.insta_title}>
              <h2>Instagram &rarr;</h2>
            </div>
            <div className={styles.insta_nametag}>
              <Image
                alt="nametag"
                src="/felipebattistotti_nametag.png"
                height={250}
                width={250}
                quality={100}
                priority={true}
              />
            </div>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <span>
          Copyright &#169; {new Date().getFullYear()} - Felipe Battistotti | CNPJ: 38.055.908/0001-75 - Todos os direitos reservados&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;➡️&#160;
          <a
            href="https://nextjs.org"
            target="_blank"
            rel="noreferrer"
          >
            Feito com Next.js
          </a>
        </span>
      </footer>
    </div>
  )
}

export default Home
